name: Python CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs: #running in some container
    test:
        runs-on: ubuntu-latest

        steps: #steps in which you want the workflow to run
            - name: check out code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2 
              with:
                python-version: '3.8'
            
            - name: Install dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

            - name: Run tests
              run: pytest
              
